(batch "C:\\Codes\\ai_jess_project\\Templates\\age_group_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\author_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\book_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\genre_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\language_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\pacing_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\style_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\user_template.clp")
(printout t "All the templates are registered and ready to use!!" crlf)
