(batch "C:\\Codes\\ai_jess_project\\Templates\\age_groups_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\authors_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\books_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\genres_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\languages_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\pacings_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\styles_template.clp")
(batch "C:\\Codes\\ai_jess_project\\Templates\\users_template.clp")
(printout t "All the templates are registered and ready to use!!" crlf)
