(batch "C:\\Codes\\ai_jess_project\\Facts\\Books\\book_1.clp")
(batch "C:\\Codes\\ai_jess_project\\Facts\\Books\\book_2.clp")
(batch "C:\\Codes\\ai_jess_project\\Facts\\Books\\book_3.clp")
(batch "C:\\Codes\\ai_jess_project\\Facts\\Books\\book_4.clp")
(printout t "All the facts are registered and ready to use!!" crlf)
