(deffunction read_age_group ()
  (printout t "Please enter your age group!!" crlf)
  (bind ?result (run-query* get_all_age_groups))
  (bind ?counter 1)
  (while (?result next)
    (printout t ?counter ". " (?result getString type) crlf)
    (++ ?counter)
  )
  (bind ?age_group (read))
  (return ?age_group)
)
