(deffunction read_genres ()
  (printout t "Please enter your genres!!" crlf)
  (bind ?result (run-query* get_all_genres))
  (bind ?counter 1)
  (while (?result next)
    (printout t ?counter ". " (?result getString type) crlf)
    (++ ?counter)
  )
  (bind ?genres (read))
  (return ?genres)
)
