(deffunction read_language ()
  (printout t "Please enter your language!!" crlf)
  (bind ?result (run-query* get_all_languages))
  (bind ?counter 1)
  (while (?result next)
    (printout t ?counter ". " (?result getString type) crlf)
    (++ ?counter)
  )
  (bind ?language (read))
  (return ?language)
)
