(deffunction read_style ()
  (printout t "Please enter your style!!" crlf)
  (bind ?result (run-query* get_all_styles))
  (bind ?counter 1)
  (while (?result next)
    (printout t ?counter ". " (?result getString type) crlf)
    (++ ?counter)
  )
  (bind ?style (read))
  (return ?style)
)
